# .gitleaks.toml
# Configuration for gitleaks, the secrets scanner.
# See https://github.com/gitleaks/gitleaks for more info.

title = "gitleaks config"
# Define rules for what to detect.
# This is a small subset of the default rules.
# You can find the full default rule set here:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

[allowlist]
description = "Allowlist certain paths or commits"
paths = [
    '''.gitleaks.toml''', # Allow this config file
    '''go.sum''',
]

[[rules]]
description = "AWS Access Key"
id = "aws-access-key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]

[[rules]]
description = "GitHub Personal Access Token"
id = "github-pat"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["key", "github"]

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''[aA][pP][iI]_?[kK][eE][yY].*[''|"][0-9a-zA-Z]{32,45}[''|"]'''
tags = ["key", "API"]
