# .hadolint.yaml
# Configuration for hadolint, the Dockerfile linter.
# See https://github.com/hadolint/hadolint for more info.

# You can ignore rules like this:
# ignored:
#   - DL3008 # Pin versions in apt get install
#   - SC2039 # In POSIX sh, 'local' is not supported

# You can also specify trusted registries
# trustedRegistries:
#   - docker.io
