// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: boxyagent/v1/agent.proto

package boxyagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Result
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // sent once, first frame only
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"` // sent periodically
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"` // sent in response to a pushed Command
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Result) isAgentMessage_Payload() {}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// registration_token is the single-use bootstrap token minted via
	// `boxy agent token create`. Empty on a cert-based reconnect, where the
	// mTLS handshake has already authenticated the agent.
	RegistrationToken string   `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	AgentName         string   `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ProviderTypes     []string `protobuf:"bytes,3,rep,name=provider_types,json=providerTypes,proto3" json:"provider_types,omitempty"`
	AgentVersion      string   `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *RegisterRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RegisterRequest) GetProviderTypes() []string {
	if x != nil {
		return x.ProviderTypes
	}
	return nil
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UnixTime      int64                  `protobuf:"varint,2,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	ProviderTypes []string               `protobuf:"bytes,3,rep,name=provider_types,json=providerTypes,proto3" json:"provider_types,omitempty"` // re-advertised in case of runtime capability change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *Heartbeat) GetProviderTypes() []string {
	if x != nil {
		return x.ProviderTypes
	}
	return nil
}

type CommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // correlates back to Command.command_id
	// Types that are valid to be assigned to Outcome:
	//
	//	*CommandResult_Resource
	//	*CommandResult_Status
	//	*CommandResult_Operation
	//	*CommandResult_Deleted
	//	*CommandResult_Allocate
	//	*CommandResult_Error
	Outcome       isCommandResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetOutcome() isCommandResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *CommandResult) GetResource() *ResourceResult {
	if x != nil {
		if x, ok := x.Outcome.(*CommandResult_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *CommandResult) GetStatus() *ResourceStatusResult {
	if x != nil {
		if x, ok := x.Outcome.(*CommandResult_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *CommandResult) GetOperation() *OperationResult {
	if x != nil {
		if x, ok := x.Outcome.(*CommandResult_Operation); ok {
			return x.Operation
		}
	}
	return nil
}

func (x *CommandResult) GetDeleted() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Outcome.(*CommandResult_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

func (x *CommandResult) GetAllocate() *AllocateResult {
	if x != nil {
		if x, ok := x.Outcome.(*CommandResult_Allocate); ok {
			return x.Allocate
		}
	}
	return nil
}

func (x *CommandResult) GetError() *AgentError {
	if x != nil {
		if x, ok := x.Outcome.(*CommandResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCommandResult_Outcome interface {
	isCommandResult_Outcome()
}

type CommandResult_Resource struct {
	Resource *ResourceResult `protobuf:"bytes,2,opt,name=resource,proto3,oneof"`
}

type CommandResult_Status struct {
	Status *ResourceStatusResult `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type CommandResult_Operation struct {
	Operation *OperationResult `protobuf:"bytes,4,opt,name=operation,proto3,oneof"`
}

type CommandResult_Deleted struct {
	Deleted *emptypb.Empty `protobuf:"bytes,5,opt,name=deleted,proto3,oneof"`
}

type CommandResult_Allocate struct {
	Allocate *AllocateResult `protobuf:"bytes,6,opt,name=allocate,proto3,oneof"`
}

type CommandResult_Error struct {
	Error *AgentError `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*CommandResult_Resource) isCommandResult_Outcome() {}

func (*CommandResult_Status) isCommandResult_Outcome() {}

func (*CommandResult_Operation) isCommandResult_Outcome() {}

func (*CommandResult_Deleted) isCommandResult_Outcome() {}

func (*CommandResult_Allocate) isCommandResult_Outcome() {}

func (*CommandResult_Error) isCommandResult_Outcome() {}

type AgentError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentError) Reset() {
	*x = AgentError{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentError) ProtoMessage() {}

func (x *AgentError) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentError.ProtoReflect.Descriptor instead.
func (*AgentError) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Registered
	//	*ServerMessage_Command
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegistered() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *ServerMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Registered struct {
	Registered *RegisterResponse `protobuf:"bytes,1,opt,name=registered,proto3,oneof"` // ack for RegisterRequest
}

type ServerMessage_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

func (*ServerMessage_Registered) isServerMessage_Payload() {}

func (*ServerMessage_Command) isServerMessage_Payload() {}

type RegisterResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// client_certificate_pem/client_private_key_pem/ca_certificate_pem are
	// populated only on a token-based (first-time) registration, not on a
	// cert-based reconnect. The private key is generated fresh per agent and
	// sent exactly once here — the server never persists it (see
	// pki.IssueAgentCert and docs/adr/0005-remote-agent-transport-and-registration.md).
	ClientCertificatePem     []byte `protobuf:"bytes,2,opt,name=client_certificate_pem,json=clientCertificatePem,proto3" json:"client_certificate_pem,omitempty"`
	ClientPrivateKeyPem      []byte `protobuf:"bytes,5,opt,name=client_private_key_pem,json=clientPrivateKeyPem,proto3" json:"client_private_key_pem,omitempty"`
	CaCertificatePem         []byte `protobuf:"bytes,3,opt,name=ca_certificate_pem,json=caCertificatePem,proto3" json:"ca_certificate_pem,omitempty"`
	HeartbeatIntervalSeconds int32  `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetClientCertificatePem() []byte {
	if x != nil {
		return x.ClientCertificatePem
	}
	return nil
}

func (x *RegisterResponse) GetClientPrivateKeyPem() []byte {
	if x != nil {
		return x.ClientPrivateKeyPem
	}
	return nil
}

func (x *RegisterResponse) GetCaCertificatePem() []byte {
	if x != nil {
		return x.CaCertificatePem
	}
	return nil
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type Command struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CommandId    string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // server-generated correlation id
	ProviderType string                 `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*Command_Create
	//	*Command_Read
	//	*Command_Update
	//	*Command_Delete
	//	*Command_Allocate
	Op            isCommand_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *Command) GetOp() isCommand_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Command) GetCreate() *CreateCommand {
	if x != nil {
		if x, ok := x.Op.(*Command_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *Command) GetRead() *ReadCommand {
	if x != nil {
		if x, ok := x.Op.(*Command_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Command) GetUpdate() *UpdateCommand {
	if x != nil {
		if x, ok := x.Op.(*Command_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *Command) GetDelete() *DeleteCommand {
	if x != nil {
		if x, ok := x.Op.(*Command_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Command) GetAllocate() *AllocateCommand {
	if x != nil {
		if x, ok := x.Op.(*Command_Allocate); ok {
			return x.Allocate
		}
	}
	return nil
}

type isCommand_Op interface {
	isCommand_Op()
}

type Command_Create struct {
	Create *CreateCommand `protobuf:"bytes,3,opt,name=create,proto3,oneof"`
}

type Command_Read struct {
	Read *ReadCommand `protobuf:"bytes,4,opt,name=read,proto3,oneof"`
}

type Command_Update struct {
	Update *UpdateCommand `protobuf:"bytes,5,opt,name=update,proto3,oneof"`
}

type Command_Delete struct {
	Delete *DeleteCommand `protobuf:"bytes,6,opt,name=delete,proto3,oneof"`
}

type Command_Allocate struct {
	Allocate *AllocateCommand `protobuf:"bytes,7,opt,name=allocate,proto3,oneof"`
}

func (*Command_Create) isCommand_Op() {}

func (*Command_Read) isCommand_Op() {}

func (*Command_Update) isCommand_Op() {}

func (*Command_Delete) isCommand_Op() {}

func (*Command_Allocate) isCommand_Op() {}

// config_json/operation_json carry providersdk.Driver's `cfg any` /
// `Operation interface{}` across the wire as opaque, already-JSON-encoded
// bytes rather than typed proto messages, preserving the existing
// per-driver-opaque-config contract instead of coupling the wire schema to
// every current and future driver.
type CreateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommand) Reset() {
	*x = CreateCommand{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommand) ProtoMessage() {}

func (x *CreateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommand.ProtoReflect.Descriptor instead.
func (*CreateCommand) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCommand) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ReadCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCommand) Reset() {
	*x = ReadCommand{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCommand) ProtoMessage() {}

func (x *ReadCommand) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCommand.ProtoReflect.Descriptor instead.
func (*ReadCommand) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ReadCommand) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type UpdateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	OperationJson []byte                 `protobuf:"bytes,2,opt,name=operation_json,json=operationJson,proto3" json:"operation_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommand) Reset() {
	*x = UpdateCommand{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommand) ProtoMessage() {}

func (x *UpdateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommand.ProtoReflect.Descriptor instead.
func (*UpdateCommand) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCommand) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpdateCommand) GetOperationJson() []byte {
	if x != nil {
		return x.OperationJson
	}
	return nil
}

type DeleteCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommand) Reset() {
	*x = DeleteCommand{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommand) ProtoMessage() {}

func (x *DeleteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommand.ProtoReflect.Descriptor instead.
func (*DeleteCommand) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCommand) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type AllocateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateCommand) Reset() {
	*x = AllocateCommand{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateCommand) ProtoMessage() {}

func (x *AllocateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateCommand.ProtoReflect.Descriptor instead.
func (*AllocateCommand) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AllocateCommand) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ResourceResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConnectionInfo map[string]string      `protobuf:"bytes,2,rep,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata       map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceResult) Reset() {
	*x = ResourceResult{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResult) ProtoMessage() {}

func (x *ResourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResult.ProtoReflect.Descriptor instead.
func (*ResourceResult) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceResult) GetConnectionInfo() map[string]string {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

func (x *ResourceResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResourceStatusResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceStatusResult) Reset() {
	*x = ResourceStatusResult{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatusResult) ProtoMessage() {}

func (x *ResourceStatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatusResult.ProtoReflect.Descriptor instead.
func (*ResourceStatusResult) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ResourceStatusResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceStatusResult) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type OperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       map[string]string      `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *OperationResult) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// properties_json carries providersdk.Driver.Allocate's `map[string]any`
// result as opaque JSON bytes rather than a protobuf map, since a protobuf
// map requires a single uniform value type and the Allocate contract does
// not constrain property values to strings (today's drivers happen to only
// produce strings via GuestAccessDetails, but the interface itself allows
// any JSON-representable value).
type AllocateResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PropertiesJson []byte                 `protobuf:"bytes,1,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllocateResult) Reset() {
	*x = AllocateResult{}
	mi := &file_boxyagent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResult) ProtoMessage() {}

func (x *AllocateResult) ProtoReflect() protoreflect.Message {
	mi := &file_boxyagent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResult.ProtoReflect.Descriptor instead.
func (*AllocateResult) Descriptor() ([]byte, []int) {
	return file_boxyagent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *AllocateResult) GetPropertiesJson() []byte {
	if x != nil {
		return x.PropertiesJson
	}
	return nil
}

var File_boxyagent_v1_agent_proto protoreflect.FileDescriptor

const file_boxyagent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18boxyagent/v1/agent.proto\x12\fboxyagent.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\x01\n" +
	"\fAgentMessage\x12;\n" +
	"\bregister\x18\x01 \x01(\v2\x1d.boxyagent.v1.RegisterRequestH\x00R\bregister\x127\n" +
	"\theartbeat\x18\x02 \x01(\v2\x17.boxyagent.v1.HeartbeatH\x00R\theartbeat\x125\n" +
	"\x06result\x18\x03 \x01(\v2\x1b.boxyagent.v1.CommandResultH\x00R\x06resultB\t\n" +
	"\apayload\"\xab\x01\n" +
	"\x0fRegisterRequest\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12%\n" +
	"\x0eprovider_types\x18\x03 \x03(\tR\rproviderTypes\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"j\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tunix_time\x18\x02 \x01(\x03R\bunixTime\x12%\n" +
	"\x0eprovider_types\x18\x03 \x03(\tR\rproviderTypes\"\x94\x03\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12:\n" +
	"\bresource\x18\x02 \x01(\v2\x1c.boxyagent.v1.ResourceResultH\x00R\bresource\x12<\n" +
	"\x06status\x18\x03 \x01(\v2\".boxyagent.v1.ResourceStatusResultH\x00R\x06status\x12=\n" +
	"\toperation\x18\x04 \x01(\v2\x1d.boxyagent.v1.OperationResultH\x00R\toperation\x122\n" +
	"\adeleted\x18\x05 \x01(\v2\x16.google.protobuf.EmptyH\x00R\adeleted\x12:\n" +
	"\ballocate\x18\x06 \x01(\v2\x1c.boxyagent.v1.AllocateResultH\x00R\ballocate\x120\n" +
	"\x05error\x18\a \x01(\v2\x18.boxyagent.v1.AgentErrorH\x00R\x05errorB\t\n" +
	"\aoutcome\"&\n" +
	"\n" +
	"AgentError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8f\x01\n" +
	"\rServerMessage\x12@\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x1e.boxyagent.v1.RegisterResponseH\x00R\n" +
	"registered\x121\n" +
	"\acommand\x18\x02 \x01(\v2\x15.boxyagent.v1.CommandH\x00R\acommandB\t\n" +
	"\apayload\"\x84\x02\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x124\n" +
	"\x16client_certificate_pem\x18\x02 \x01(\fR\x14clientCertificatePem\x123\n" +
	"\x16client_private_key_pem\x18\x05 \x01(\fR\x13clientPrivateKeyPem\x12,\n" +
	"\x12ca_certificate_pem\x18\x03 \x01(\fR\x10caCertificatePem\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\x05R\x18heartbeatIntervalSeconds\"\xe6\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x125\n" +
	"\x06create\x18\x03 \x01(\v2\x1b.boxyagent.v1.CreateCommandH\x00R\x06create\x12/\n" +
	"\x04read\x18\x04 \x01(\v2\x19.boxyagent.v1.ReadCommandH\x00R\x04read\x125\n" +
	"\x06update\x18\x05 \x01(\v2\x1b.boxyagent.v1.UpdateCommandH\x00R\x06update\x125\n" +
	"\x06delete\x18\x06 \x01(\v2\x1b.boxyagent.v1.DeleteCommandH\x00R\x06delete\x12;\n" +
	"\ballocate\x18\a \x01(\v2\x1d.boxyagent.v1.AllocateCommandH\x00R\ballocateB\x04\n" +
	"\x02op\"0\n" +
	"\rCreateCommand\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\".\n" +
	"\vReadCommand\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"W\n" +
	"\rUpdateCommand\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12%\n" +
	"\x0eoperation_json\x18\x02 \x01(\fR\roperationJson\"0\n" +
	"\rDeleteCommand\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"2\n" +
	"\x0fAllocateCommand\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"\xc3\x02\n" +
	"\x0eResourceResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12Y\n" +
	"\x0fconnection_info\x18\x02 \x03(\v20.boxyagent.v1.ResourceResult.ConnectionInfoEntryR\x0econnectionInfo\x12F\n" +
	"\bmetadata\x18\x03 \x03(\v2*.boxyagent.v1.ResourceResult.MetadataEntryR\bmetadata\x1aA\n" +
	"\x13ConnectionInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x14ResourceStatusResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\x93\x01\n" +
	"\x0fOperationResult\x12D\n" +
	"\aoutputs\x18\x01 \x03(\v2*.boxyagent.v1.OperationResult.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0eAllocateResult\x12'\n" +
	"\x0fproperties_json\x18\x01 \x01(\fR\x0epropertiesJson2_\n" +
	"\x15AgentTransportService\x12F\n" +
	"\aConnect\x12\x1a.boxyagent.v1.AgentMessage\x1a\x1b.boxyagent.v1.ServerMessage(\x010\x01B@Z>github.com/Geogboe/boxy/pkg/agentproto/boxyagentv1;boxyagentv1b\x06proto3"

var (
	file_boxyagent_v1_agent_proto_rawDescOnce sync.Once
	file_boxyagent_v1_agent_proto_rawDescData []byte
)

func file_boxyagent_v1_agent_proto_rawDescGZIP() []byte {
	file_boxyagent_v1_agent_proto_rawDescOnce.Do(func() {
		file_boxyagent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boxyagent_v1_agent_proto_rawDesc), len(file_boxyagent_v1_agent_proto_rawDesc)))
	})
	return file_boxyagent_v1_agent_proto_rawDescData
}

var file_boxyagent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_boxyagent_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),         // 0: boxyagent.v1.AgentMessage
	(*RegisterRequest)(nil),      // 1: boxyagent.v1.RegisterRequest
	(*Heartbeat)(nil),            // 2: boxyagent.v1.Heartbeat
	(*CommandResult)(nil),        // 3: boxyagent.v1.CommandResult
	(*AgentError)(nil),           // 4: boxyagent.v1.AgentError
	(*ServerMessage)(nil),        // 5: boxyagent.v1.ServerMessage
	(*RegisterResponse)(nil),     // 6: boxyagent.v1.RegisterResponse
	(*Command)(nil),              // 7: boxyagent.v1.Command
	(*CreateCommand)(nil),        // 8: boxyagent.v1.CreateCommand
	(*ReadCommand)(nil),          // 9: boxyagent.v1.ReadCommand
	(*UpdateCommand)(nil),        // 10: boxyagent.v1.UpdateCommand
	(*DeleteCommand)(nil),        // 11: boxyagent.v1.DeleteCommand
	(*AllocateCommand)(nil),      // 12: boxyagent.v1.AllocateCommand
	(*ResourceResult)(nil),       // 13: boxyagent.v1.ResourceResult
	(*ResourceStatusResult)(nil), // 14: boxyagent.v1.ResourceStatusResult
	(*OperationResult)(nil),      // 15: boxyagent.v1.OperationResult
	(*AllocateResult)(nil),       // 16: boxyagent.v1.AllocateResult
	nil,                          // 17: boxyagent.v1.ResourceResult.ConnectionInfoEntry
	nil,                          // 18: boxyagent.v1.ResourceResult.MetadataEntry
	nil,                          // 19: boxyagent.v1.OperationResult.OutputsEntry
	(*emptypb.Empty)(nil),        // 20: google.protobuf.Empty
}
var file_boxyagent_v1_agent_proto_depIdxs = []int32{
	1,  // 0: boxyagent.v1.AgentMessage.register:type_name -> boxyagent.v1.RegisterRequest
	2,  // 1: boxyagent.v1.AgentMessage.heartbeat:type_name -> boxyagent.v1.Heartbeat
	3,  // 2: boxyagent.v1.AgentMessage.result:type_name -> boxyagent.v1.CommandResult
	13, // 3: boxyagent.v1.CommandResult.resource:type_name -> boxyagent.v1.ResourceResult
	14, // 4: boxyagent.v1.CommandResult.status:type_name -> boxyagent.v1.ResourceStatusResult
	15, // 5: boxyagent.v1.CommandResult.operation:type_name -> boxyagent.v1.OperationResult
	20, // 6: boxyagent.v1.CommandResult.deleted:type_name -> google.protobuf.Empty
	16, // 7: boxyagent.v1.CommandResult.allocate:type_name -> boxyagent.v1.AllocateResult
	4,  // 8: boxyagent.v1.CommandResult.error:type_name -> boxyagent.v1.AgentError
	6,  // 9: boxyagent.v1.ServerMessage.registered:type_name -> boxyagent.v1.RegisterResponse
	7,  // 10: boxyagent.v1.ServerMessage.command:type_name -> boxyagent.v1.Command
	8,  // 11: boxyagent.v1.Command.create:type_name -> boxyagent.v1.CreateCommand
	9,  // 12: boxyagent.v1.Command.read:type_name -> boxyagent.v1.ReadCommand
	10, // 13: boxyagent.v1.Command.update:type_name -> boxyagent.v1.UpdateCommand
	11, // 14: boxyagent.v1.Command.delete:type_name -> boxyagent.v1.DeleteCommand
	12, // 15: boxyagent.v1.Command.allocate:type_name -> boxyagent.v1.AllocateCommand
	17, // 16: boxyagent.v1.ResourceResult.connection_info:type_name -> boxyagent.v1.ResourceResult.ConnectionInfoEntry
	18, // 17: boxyagent.v1.ResourceResult.metadata:type_name -> boxyagent.v1.ResourceResult.MetadataEntry
	19, // 18: boxyagent.v1.OperationResult.outputs:type_name -> boxyagent.v1.OperationResult.OutputsEntry
	0,  // 19: boxyagent.v1.AgentTransportService.Connect:input_type -> boxyagent.v1.AgentMessage
	5,  // 20: boxyagent.v1.AgentTransportService.Connect:output_type -> boxyagent.v1.ServerMessage
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_boxyagent_v1_agent_proto_init() }
func file_boxyagent_v1_agent_proto_init() {
	if File_boxyagent_v1_agent_proto != nil {
		return
	}
	file_boxyagent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Result)(nil),
	}
	file_boxyagent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*CommandResult_Resource)(nil),
		(*CommandResult_Status)(nil),
		(*CommandResult_Operation)(nil),
		(*CommandResult_Deleted)(nil),
		(*CommandResult_Allocate)(nil),
		(*CommandResult_Error)(nil),
	}
	file_boxyagent_v1_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerMessage_Registered)(nil),
		(*ServerMessage_Command)(nil),
	}
	file_boxyagent_v1_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*Command_Create)(nil),
		(*Command_Read)(nil),
		(*Command_Update)(nil),
		(*Command_Delete)(nil),
		(*Command_Allocate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boxyagent_v1_agent_proto_rawDesc), len(file_boxyagent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boxyagent_v1_agent_proto_goTypes,
		DependencyIndexes: file_boxyagent_v1_agent_proto_depIdxs,
		MessageInfos:      file_boxyagent_v1_agent_proto_msgTypes,
	}.Build()
	File_boxyagent_v1_agent_proto = out.File
	file_boxyagent_v1_agent_proto_goTypes = nil
	file_boxyagent_v1_agent_proto_depIdxs = nil
}
