// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: boxyagent/v1/agent.proto

package boxyagentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentTransportService_Connect_FullMethodName = "/boxyagent.v1.AgentTransportService/Connect"
)

// AgentTransportServiceClient is the client API for AgentTransportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentTransport is the single service a remote boxy agent uses to
// communicate with a boxy server. The agent dials out and opens exactly one
// long-lived bidirectional stream per connection (NAT/firewall-friendly);
// the server pushes Commands down that same stream and reads CommandResults
// back. See docs/adr/0005-remote-agent-transport-and-registration.md.
type AgentTransportServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
}

type agentTransportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentTransportServiceClient(cc grpc.ClientConnInterface) AgentTransportServiceClient {
	return &agentTransportServiceClient{cc}
}

func (c *agentTransportServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentTransportService_ServiceDesc.Streams[0], AgentTransportService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTransportService_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

// AgentTransportServiceServer is the server API for AgentTransportService service.
// All implementations must embed UnimplementedAgentTransportServiceServer
// for forward compatibility.
//
// AgentTransport is the single service a remote boxy agent uses to
// communicate with a boxy server. The agent dials out and opens exactly one
// long-lived bidirectional stream per connection (NAT/firewall-friendly);
// the server pushes Commands down that same stream and reads CommandResults
// back. See docs/adr/0005-remote-agent-transport-and-registration.md.
type AgentTransportServiceServer interface {
	Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	mustEmbedUnimplementedAgentTransportServiceServer()
}

// UnimplementedAgentTransportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentTransportServiceServer struct{}

func (UnimplementedAgentTransportServiceServer) Connect(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentTransportServiceServer) mustEmbedUnimplementedAgentTransportServiceServer() {}
func (UnimplementedAgentTransportServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentTransportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentTransportServiceServer will
// result in compilation errors.
type UnsafeAgentTransportServiceServer interface {
	mustEmbedUnimplementedAgentTransportServiceServer()
}

func RegisterAgentTransportServiceServer(s grpc.ServiceRegistrar, srv AgentTransportServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentTransportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentTransportService_ServiceDesc, srv)
}

func _AgentTransportService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentTransportServiceServer).Connect(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTransportService_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

// AgentTransportService_ServiceDesc is the grpc.ServiceDesc for AgentTransportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentTransportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boxyagent.v1.AgentTransportService",
	HandlerType: (*AgentTransportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentTransportService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "boxyagent/v1/agent.proto",
}
