// Command help-gen converts the operator help Markdown source into the
// embedded Go HTML template used by the authenticated dashboard.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	goldmarkhtml "github.com/yuin/goldmark/renderer/html"
)

func main() {
	input := flag.String("input", "docs/help/index.md", "source Markdown path")
	output := flag.String("output", "internal/server/templates/help.html", "output Go template path")
	flag.Parse()
	if err := generate(*input, *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(input, output string) error {
	source, err := os.ReadFile(input)
	if err != nil {
		return fmt.Errorf("read help source %q: %w", input, err)
	}
	content, err := render(source)
	if err != nil {
		return fmt.Errorf("render help source %q: %w", input, err)
	}
	if err := os.WriteFile(output, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write help template %q: %w", output, err)
	}
	if err := os.Chmod(output, 0o644); err != nil { //nolint:gosec // generated dashboard template is intentionally world-readable
		return fmt.Errorf("set help template permissions %q: %w", output, err)
	}
	return nil
}

func render(source []byte) (string, error) {
	var body bytes.Buffer
	parser := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithRendererOptions(goldmarkhtml.WithXHTML()),
	)
	if err := parser.Convert(source, &body); err != nil {
		return "", err
	}

	return "<!-- Code generated by cmd/help-gen from docs/help/index.md; DO NOT EDIT. -->\n" +
		"{{define \"title\"}}Help{{end}}\n" +
		"{{define \"content\"}}\n" +
		"<article class=\"help-content\">\n" + body.String() +
		"</article>\n" +
		"{{end}}\n", nil
}
