// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: pkg/provider/proto/provider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider to use (docker, hyperv, kvm, etc.)
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Resource specification
	Spec          *ResourceSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProvisionRequest) GetSpec() *ResourceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ProvisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provisioned resource
	Resource      *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DestroyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Resource to destroy
	Resource      *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *DestroyRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DestroyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Resource to check status for
	Resource      *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *GetStatusRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current resource status
	Status        *ResourceStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetStatus() *ResourceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetConnectionInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Resource to get connection info for
	Resource      *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionInfoRequest) Reset() {
	*x = GetConnectionInfoRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionInfoRequest) ProtoMessage() {}

func (x *GetConnectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetConnectionInfoRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *GetConnectionInfoRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetConnectionInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection information
	ConnectionInfo *ConnectionInfo `protobuf:"bytes,1,opt,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConnectionInfoResponse) Reset() {
	*x = GetConnectionInfoResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionInfoResponse) ProtoMessage() {}

func (x *GetConnectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionInfoResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetConnectionInfoResponse) GetConnectionInfo() *ConnectionInfo {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider to health check
	ProviderName  string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Healthy status
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Optional message (error details if unhealthy)
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Resource to execute command in
	Resource *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Command to execute (array of strings)
	Command       []string `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ExecRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ExecRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exit code
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Standard output
	Stdout string `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard error
	Stderr string `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Error message (if execution failed)
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{11}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Resource to update
	Resource *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Action to perform (power-on, power-off, restart, snapshot-create, etc.)
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// Action-specific parameters
	Params        map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *UpdateRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *UpdateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Updated resource (may have new metadata)
	Resource *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Error message (if update failed)
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *UpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique agent ID (from certificate CN)
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Agent address (host:port) for server to connect
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// List of provider names available on this agent
	Providers []string `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	// Agent version
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Agent hostname
	Hostname string `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Agent OS
	Os string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	// Agent architecture
	Arch          string `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message (error details if failed)
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Server-assigned configuration (optional)
	Config        map[string]string `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current resource counts per provider
	ProviderStats []*ProviderStats `protobuf:"bytes,2,rep,name=provider_stats,json=providerStats,proto3" json:"provider_stats,omitempty"`
	// Agent uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetProviderStats() []*ProviderStats {
	if x != nil {
		return x.ProviderStats
	}
	return nil
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Server time (for clock sync check)
	ServerTime    int64 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type ListProvidersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ListProvidersRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListProvidersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available providers
	Providers     []*ProviderInfo `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ResourceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type (container, vm, process)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Provider type (docker, hyperv, kvm, vmware)
	ProviderType string `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	// Image or template name
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// CPU allocation
	Cpus int32 `protobuf:"varint,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	// Memory in MB
	MemoryMb int32 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	// Disk size in GB
	DiskGb int32 `protobuf:"varint,6,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	// Labels (key-value pairs)
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Environment variables
	Environment map[string]string `protobuf:"bytes,8,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Extra configuration (flexible JSON)
	ExtraConfig   map[string]string `protobuf:"bytes,9,rep,name=extra_config,json=extraConfig,proto3" json:"extra_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{20}
}

func (x *ResourceSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceSpec) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ResourceSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ResourceSpec) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *ResourceSpec) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceSpec) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *ResourceSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ResourceSpec) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ResourceSpec) GetExtraConfig() map[string]string {
	if x != nil {
		return x.ExtraConfig
	}
	return nil
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique resource ID (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Pool ID this resource belongs to
	PoolId string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// Sandbox ID (if allocated)
	SandboxId string `protobuf:"bytes,3,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Resource type
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Resource state
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// Provider type
	ProviderType string `protobuf:"bytes,6,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	// Provider-specific ID
	ProviderId string `protobuf:"bytes,7,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Resource specification
	Spec map[string]string `protobuf:"bytes,8,rep,name=spec,proto3" json:"spec,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Provider metadata
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation timestamp (Unix seconds)
	CreatedAt int64 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp (Unix seconds)
	UpdatedAt int64 `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Expiration timestamp (Unix seconds, 0 if no expiration)
	ExpiresAt     int64 `protobuf:"varint,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{21}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *Resource) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Resource) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *Resource) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Resource) GetSpec() map[string]string {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Resource) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Resource) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ResourceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource state
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Healthy flag
	Healthy bool `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Status message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Last check timestamp (Unix seconds)
	LastCheck int64 `protobuf:"varint,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	// Uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// CPU usage percentage (0-100)
	CpuUsage float64 `protobuf:"fixed64,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Memory used in bytes
	MemoryUsed    uint64 `protobuf:"varint,7,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceStatus) Reset() {
	*x = ResourceStatus{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatus) ProtoMessage() {}

func (x *ResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatus.ProtoReflect.Descriptor instead.
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{22}
}

func (x *ResourceStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ResourceStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ResourceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResourceStatus) GetLastCheck() int64 {
	if x != nil {
		return x.LastCheck
	}
	return 0
}

func (x *ResourceStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ResourceStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ResourceStatus) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

type ConnectionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection type (ssh, rdp, http, docker-exec, etc.)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Host address
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// Port number
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Username
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// Password (encrypted in transit via TLS)
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// SSH private key (if applicable)
	SshKey string `protobuf:"bytes,6,opt,name=ssh_key,json=sshKey,proto3" json:"ssh_key,omitempty"`
	// Extra connection fields (flexible)
	ExtraFields   map[string]string `protobuf:"bytes,7,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{23}
}

func (x *ConnectionInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConnectionInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectionInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectionInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConnectionInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectionInfo) GetSshKey() string {
	if x != nil {
		return x.SshKey
	}
	return ""
}

func (x *ConnectionInfo) GetExtraFields() map[string]string {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

type ProviderInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider name (docker, hyperv, etc.)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Provider type (container, vm, process)
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Healthy status
	Healthy bool `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Version information
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Last health check timestamp
	LastHealthCheck int64 `protobuf:"varint,5,opt,name=last_health_check,json=lastHealthCheck,proto3" json:"last_health_check,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{24}
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderInfo) GetLastHealthCheck() int64 {
	if x != nil {
		return x.LastHealthCheck
	}
	return 0
}

type ProviderStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider name
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Total resources managed
	TotalResources int32 `protobuf:"varint,2,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	// Ready resources
	ReadyResources int32 `protobuf:"varint,3,opt,name=ready_resources,json=readyResources,proto3" json:"ready_resources,omitempty"`
	// Allocated resources
	AllocatedResources int32 `protobuf:"varint,4,opt,name=allocated_resources,json=allocatedResources,proto3" json:"allocated_resources,omitempty"`
	// Error resources
	ErrorResources int32 `protobuf:"varint,5,opt,name=error_resources,json=errorResources,proto3" json:"error_resources,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderStats) Reset() {
	*x = ProviderStats{}
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStats) ProtoMessage() {}

func (x *ProviderStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_provider_proto_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStats.ProtoReflect.Descriptor instead.
func (*ProviderStats) Descriptor() ([]byte, []int) {
	return file_pkg_provider_proto_provider_proto_rawDescGZIP(), []int{25}
}

func (x *ProviderStats) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProviderStats) GetTotalResources() int32 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *ProviderStats) GetReadyResources() int32 {
	if x != nil {
		return x.ReadyResources
	}
	return 0
}

func (x *ProviderStats) GetAllocatedResources() int32 {
	if x != nil {
		return x.AllocatedResources
	}
	return 0
}

func (x *ProviderStats) GetErrorResources() int32 {
	if x != nil {
		return x.ErrorResources
	}
	return 0
}

var File_pkg_provider_proto_provider_proto protoreflect.FileDescriptor

const file_pkg_provider_proto_provider_proto_rawDesc = "" +
	"\n" +
	"!pkg/provider/proto/provider.proto\x12\bprovider\"c\n" +
	"\x10ProvisionRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12*\n" +
	"\x04spec\x18\x02 \x01(\v2\x16.provider.ResourceSpecR\x04spec\"C\n" +
	"\x11ProvisionResponse\x12.\n" +
	"\bresource\x18\x01 \x01(\v2\x12.provider.ResourceR\bresource\"e\n" +
	"\x0eDestroyRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.provider.ResourceR\bresource\"+\n" +
	"\x0fDestroyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x10GetStatusRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.provider.ResourceR\bresource\"E\n" +
	"\x11GetStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.provider.ResourceStatusR\x06status\"o\n" +
	"\x18GetConnectionInfoRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.provider.ResourceR\bresource\"^\n" +
	"\x19GetConnectionInfoResponse\x12A\n" +
	"\x0fconnection_info\x18\x01 \x01(\v2\x18.provider.ConnectionInfoR\x0econnectionInfo\"9\n" +
	"\x12HealthCheckRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"|\n" +
	"\vExecRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.provider.ResourceR\bresource\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\"q\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xf4\x01\n" +
	"\rUpdateRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.provider.ResourceR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12;\n" +
	"\x06params\x18\x04 \x03(\v2#.provider.UpdateRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.provider.ResourceR\bresource\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xbe\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\"\xc1\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x06config\x18\x03 \x03(\v2&.provider.RegisterResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12>\n" +
	"\x0eprovider_stats\x18\x02 \x03(\v2\x17.provider.ProviderStatsR\rproviderStats\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"N\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"1\n" +
	"\x14ListProvidersRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"M\n" +
	"\x15ListProvidersResponse\x124\n" +
	"\tproviders\x18\x01 \x03(\v2\x16.provider.ProviderInfoR\tproviders\"\xb5\x04\n" +
	"\fResourceSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x12\n" +
	"\x04cpus\x18\x04 \x01(\x05R\x04cpus\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\x06 \x01(\x05R\x06diskGb\x12:\n" +
	"\x06labels\x18\a \x03(\v2\".provider.ResourceSpec.LabelsEntryR\x06labels\x12I\n" +
	"\venvironment\x18\b \x03(\v2'.provider.ResourceSpec.EnvironmentEntryR\venvironment\x12J\n" +
	"\fextra_config\x18\t \x03(\v2'.provider.ResourceSpec.ExtraConfigEntryR\vextraConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10ExtraConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x04\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x03 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12#\n" +
	"\rprovider_type\x18\x06 \x01(\tR\fproviderType\x12\x1f\n" +
	"\vprovider_id\x18\a \x01(\tR\n" +
	"providerId\x120\n" +
	"\x04spec\x18\b \x03(\v2\x1c.provider.Resource.SpecEntryR\x04spec\x12<\n" +
	"\bmetadata\x18\t \x03(\v2 .provider.Resource.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\x03R\texpiresAt\x1a7\n" +
	"\tSpecEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x0eResourceStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"last_check\x18\x04 \x01(\x03R\tlastCheck\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x01R\bcpuUsage\x12\x1f\n" +
	"\vmemory_used\x18\a \x01(\x04R\n" +
	"memoryUsed\"\xab\x02\n" +
	"\x0eConnectionInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x17\n" +
	"\assh_key\x18\x06 \x01(\tR\x06sshKey\x12L\n" +
	"\fextra_fields\x18\a \x03(\v2).provider.ConnectionInfo.ExtraFieldsEntryR\vextraFields\x1a>\n" +
	"\x10ExtraFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12*\n" +
	"\x11last_health_check\x18\x05 \x01(\x03R\x0flastHealthCheck\"\xe0\x01\n" +
	"\rProviderStats\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12'\n" +
	"\x0ftotal_resources\x18\x02 \x01(\x05R\x0etotalResources\x12'\n" +
	"\x0fready_resources\x18\x03 \x01(\x05R\x0ereadyResources\x12/\n" +
	"\x13allocated_resources\x18\x04 \x01(\x05R\x12allocatedResources\x12'\n" +
	"\x0ferror_resources\x18\x05 \x01(\x05R\x0eerrorResources2\xfb\x03\n" +
	"\x0fProviderService\x12D\n" +
	"\tProvision\x12\x1a.provider.ProvisionRequest\x1a\x1b.provider.ProvisionResponse\x12>\n" +
	"\aDestroy\x12\x18.provider.DestroyRequest\x1a\x19.provider.DestroyResponse\x12D\n" +
	"\tGetStatus\x12\x1a.provider.GetStatusRequest\x1a\x1b.provider.GetStatusResponse\x12\\\n" +
	"\x11GetConnectionInfo\x12\".provider.GetConnectionInfoRequest\x1a#.provider.GetConnectionInfoResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.provider.HealthCheckRequest\x1a\x1d.provider.HealthCheckResponse\x125\n" +
	"\x04Exec\x12\x15.provider.ExecRequest\x1a\x16.provider.ExecResponse\x12;\n" +
	"\x06Update\x12\x17.provider.UpdateRequest\x1a\x18.provider.UpdateResponse2\xe9\x01\n" +
	"\fAgentService\x12A\n" +
	"\bRegister\x12\x19.provider.RegisterRequest\x1a\x1a.provider.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.provider.HeartbeatRequest\x1a\x1b.provider.HeartbeatResponse\x12P\n" +
	"\rListProviders\x12\x1e.provider.ListProvidersRequest\x1a\x1f.provider.ListProvidersResponseB,Z*github.com/Geogboe/boxy/pkg/provider/protob\x06proto3"

var (
	file_pkg_provider_proto_provider_proto_rawDescOnce sync.Once
	file_pkg_provider_proto_provider_proto_rawDescData []byte
)

func file_pkg_provider_proto_provider_proto_rawDescGZIP() []byte {
	file_pkg_provider_proto_provider_proto_rawDescOnce.Do(func() {
		file_pkg_provider_proto_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_provider_proto_provider_proto_rawDesc), len(file_pkg_provider_proto_provider_proto_rawDesc)))
	})
	return file_pkg_provider_proto_provider_proto_rawDescData
}

var file_pkg_provider_proto_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_pkg_provider_proto_provider_proto_goTypes = []any{
	(*ProvisionRequest)(nil),          // 0: provider.ProvisionRequest
	(*ProvisionResponse)(nil),         // 1: provider.ProvisionResponse
	(*DestroyRequest)(nil),            // 2: provider.DestroyRequest
	(*DestroyResponse)(nil),           // 3: provider.DestroyResponse
	(*GetStatusRequest)(nil),          // 4: provider.GetStatusRequest
	(*GetStatusResponse)(nil),         // 5: provider.GetStatusResponse
	(*GetConnectionInfoRequest)(nil),  // 6: provider.GetConnectionInfoRequest
	(*GetConnectionInfoResponse)(nil), // 7: provider.GetConnectionInfoResponse
	(*HealthCheckRequest)(nil),        // 8: provider.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 9: provider.HealthCheckResponse
	(*ExecRequest)(nil),               // 10: provider.ExecRequest
	(*ExecResponse)(nil),              // 11: provider.ExecResponse
	(*UpdateRequest)(nil),             // 12: provider.UpdateRequest
	(*UpdateResponse)(nil),            // 13: provider.UpdateResponse
	(*RegisterRequest)(nil),           // 14: provider.RegisterRequest
	(*RegisterResponse)(nil),          // 15: provider.RegisterResponse
	(*HeartbeatRequest)(nil),          // 16: provider.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 17: provider.HeartbeatResponse
	(*ListProvidersRequest)(nil),      // 18: provider.ListProvidersRequest
	(*ListProvidersResponse)(nil),     // 19: provider.ListProvidersResponse
	(*ResourceSpec)(nil),              // 20: provider.ResourceSpec
	(*Resource)(nil),                  // 21: provider.Resource
	(*ResourceStatus)(nil),            // 22: provider.ResourceStatus
	(*ConnectionInfo)(nil),            // 23: provider.ConnectionInfo
	(*ProviderInfo)(nil),              // 24: provider.ProviderInfo
	(*ProviderStats)(nil),             // 25: provider.ProviderStats
	nil,                               // 26: provider.UpdateRequest.ParamsEntry
	nil,                               // 27: provider.RegisterResponse.ConfigEntry
	nil,                               // 28: provider.ResourceSpec.LabelsEntry
	nil,                               // 29: provider.ResourceSpec.EnvironmentEntry
	nil,                               // 30: provider.ResourceSpec.ExtraConfigEntry
	nil,                               // 31: provider.Resource.SpecEntry
	nil,                               // 32: provider.Resource.MetadataEntry
	nil,                               // 33: provider.ConnectionInfo.ExtraFieldsEntry
}
var file_pkg_provider_proto_provider_proto_depIdxs = []int32{
	20, // 0: provider.ProvisionRequest.spec:type_name -> provider.ResourceSpec
	21, // 1: provider.ProvisionResponse.resource:type_name -> provider.Resource
	21, // 2: provider.DestroyRequest.resource:type_name -> provider.Resource
	21, // 3: provider.GetStatusRequest.resource:type_name -> provider.Resource
	22, // 4: provider.GetStatusResponse.status:type_name -> provider.ResourceStatus
	21, // 5: provider.GetConnectionInfoRequest.resource:type_name -> provider.Resource
	23, // 6: provider.GetConnectionInfoResponse.connection_info:type_name -> provider.ConnectionInfo
	21, // 7: provider.ExecRequest.resource:type_name -> provider.Resource
	21, // 8: provider.UpdateRequest.resource:type_name -> provider.Resource
	26, // 9: provider.UpdateRequest.params:type_name -> provider.UpdateRequest.ParamsEntry
	21, // 10: provider.UpdateResponse.resource:type_name -> provider.Resource
	27, // 11: provider.RegisterResponse.config:type_name -> provider.RegisterResponse.ConfigEntry
	25, // 12: provider.HeartbeatRequest.provider_stats:type_name -> provider.ProviderStats
	24, // 13: provider.ListProvidersResponse.providers:type_name -> provider.ProviderInfo
	28, // 14: provider.ResourceSpec.labels:type_name -> provider.ResourceSpec.LabelsEntry
	29, // 15: provider.ResourceSpec.environment:type_name -> provider.ResourceSpec.EnvironmentEntry
	30, // 16: provider.ResourceSpec.extra_config:type_name -> provider.ResourceSpec.ExtraConfigEntry
	31, // 17: provider.Resource.spec:type_name -> provider.Resource.SpecEntry
	32, // 18: provider.Resource.metadata:type_name -> provider.Resource.MetadataEntry
	33, // 19: provider.ConnectionInfo.extra_fields:type_name -> provider.ConnectionInfo.ExtraFieldsEntry
	0,  // 20: provider.ProviderService.Provision:input_type -> provider.ProvisionRequest
	2,  // 21: provider.ProviderService.Destroy:input_type -> provider.DestroyRequest
	4,  // 22: provider.ProviderService.GetStatus:input_type -> provider.GetStatusRequest
	6,  // 23: provider.ProviderService.GetConnectionInfo:input_type -> provider.GetConnectionInfoRequest
	8,  // 24: provider.ProviderService.HealthCheck:input_type -> provider.HealthCheckRequest
	10, // 25: provider.ProviderService.Exec:input_type -> provider.ExecRequest
	12, // 26: provider.ProviderService.Update:input_type -> provider.UpdateRequest
	14, // 27: provider.AgentService.Register:input_type -> provider.RegisterRequest
	16, // 28: provider.AgentService.Heartbeat:input_type -> provider.HeartbeatRequest
	18, // 29: provider.AgentService.ListProviders:input_type -> provider.ListProvidersRequest
	1,  // 30: provider.ProviderService.Provision:output_type -> provider.ProvisionResponse
	3,  // 31: provider.ProviderService.Destroy:output_type -> provider.DestroyResponse
	5,  // 32: provider.ProviderService.GetStatus:output_type -> provider.GetStatusResponse
	7,  // 33: provider.ProviderService.GetConnectionInfo:output_type -> provider.GetConnectionInfoResponse
	9,  // 34: provider.ProviderService.HealthCheck:output_type -> provider.HealthCheckResponse
	11, // 35: provider.ProviderService.Exec:output_type -> provider.ExecResponse
	13, // 36: provider.ProviderService.Update:output_type -> provider.UpdateResponse
	15, // 37: provider.AgentService.Register:output_type -> provider.RegisterResponse
	17, // 38: provider.AgentService.Heartbeat:output_type -> provider.HeartbeatResponse
	19, // 39: provider.AgentService.ListProviders:output_type -> provider.ListProvidersResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_provider_proto_provider_proto_init() }
func file_pkg_provider_proto_provider_proto_init() {
	if File_pkg_provider_proto_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_provider_proto_provider_proto_rawDesc), len(file_pkg_provider_proto_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_provider_proto_provider_proto_goTypes,
		DependencyIndexes: file_pkg_provider_proto_provider_proto_depIdxs,
		MessageInfos:      file_pkg_provider_proto_provider_proto_msgTypes,
	}.Build()
	File_pkg_provider_proto_provider_proto = out.File
	file_pkg_provider_proto_provider_proto_goTypes = nil
	file_pkg_provider_proto_provider_proto_depIdxs = nil
}
