# Code generated by go generate; DO NOT EDIT.
# boxy installer — Windows (PowerShell)
#
# Usage:
#   irm https://raw.githubusercontent.com/Geogboe/boxy/main/scripts/install.ps1 | iex
#
# Environment variables:
#   $env:BOXY_VERSION     Pin a specific version (e.g. v0.1.8). Defaults to latest release.
#   $env:BOXY_INSTALL_DIR Override install directory. Defaults to $HOME\.local\bin.
#   $env:BOXY_DEBUG       Set to 1 for verbose output.
#   $env:BOXY_FORCE       Set to 1 to overwrite an existing installation.

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Repo       = 'Geogboe/boxy'
$InstallDir = if ($env:BOXY_INSTALL_DIR) { $env:BOXY_INSTALL_DIR } else { "$HOME\.local\bin" }
$IsDebug    = $env:BOXY_DEBUG -eq '1'
$IsForce    = $env:BOXY_FORCE -eq '1'
$BaseUrl    = $env:BOXY_BASE_URL

function Write-Info ([string]$Msg) { Write-Host "==> $Msg" -ForegroundColor Cyan }
function Write-Ok   ([string]$Msg) { Write-Host "==> $Msg" -ForegroundColor Green }
function Write-Warn ([string]$Msg) { Write-Warning $Msg }
function Write-Dbg  ([string]$Msg) { if ($IsDebug) { Write-Host "[debug] $Msg" -ForegroundColor DarkGray } }

function Get-ProcessorArchitecture {
    if ($env:PROCESSOR_ARCHITEW6432) { return $env:PROCESSOR_ARCHITEW6432 }
    return $env:PROCESSOR_ARCHITECTURE
}

function Resolve-BoxyVersion {
    if ($env:BOXY_VERSION) { return $env:BOXY_VERSION }
    Write-Info 'Fetching latest release version...'
    $ApiBase = if ($BaseUrl) { $BaseUrl } else { 'https://api.github.com' }
    $Releases = Invoke-RestMethod "$ApiBase/repos/$Repo/releases?per_page=1"
    $Tag = $Releases[0].tag_name
    if (-not $Tag) { throw 'Could not determine latest version.' }
    return $Tag
}

function Test-Checksum ([string]$Path, [string]$Expected) {
    $Stream = [System.IO.File]::OpenRead($Path)
    try {
        $Sha = [System.Security.Cryptography.SHA256]::Create()
        $Hash = $Sha.ComputeHash($Stream)
        $Actual = -join ($Hash | ForEach-Object { $_.ToString('x2') })
    } finally { $Stream.Close() }
    Write-Dbg "expected=$Expected actual=$Actual"
    if ($Actual -ne $Expected.ToLowerInvariant()) {
        throw "Checksum mismatch (expected $Expected, got $Actual)."
    }
}

function Get-ExpectedChecksum ([string]$ChecksumsPath, [string]$AssetName) {
    foreach ($Line in Get-Content -LiteralPath $ChecksumsPath) {
        $Parts = $Line -split '\s+', 2
        if ($Parts.Count -ge 2 -and $Parts[1].Trim() -eq $AssetName) { return $Parts[0].Trim() }
    }
    return $null
}

function Copy-ReleaseAsset ([string]$Source, [string]$Destination) {
    if (Test-Path -LiteralPath $Source -PathType Leaf) {
        Copy-Item -LiteralPath $Source -Destination $Destination -Force
        return
    }
    try {
        Invoke-WebRequest -Uri $Source -OutFile $Destination -UseBasicParsing
    } catch {
        $Status = $_.Exception.Response.StatusCode.value__
        if ($Status -eq 404) { throw "Release asset not found: $Source (HTTP 404)." }
        throw "Failed to download: $($_.Exception.Message)"
    }
}

function Test-InPath ([string]$Dir) {
    return ($env:Path -split ';') -contains $Dir
}

function Show-PathInstructions ([string]$Dir) {
    Write-Warning "$Dir is not in your PATH."
    Write-Host '  Add it by running:' -ForegroundColor Yellow
    Write-Host ''
    $Escaped = $Dir -replace "'", "''"
    Write-Host "  [Environment]::SetEnvironmentVariable('Path', `"`$([Environment]::GetEnvironmentVariable('Path','User'));$Escaped`", 'User')" -ForegroundColor Cyan
    Write-Host ''
    Write-Host '  Then restart your terminal.' -ForegroundColor Yellow
}

$TmpDir = $null
try {
    # ── Platform ─────────────────────────────────────────────────────────────
    $Arch = Get-ProcessorArchitecture
    if ($Arch -notin @('AMD64', 'x86_64', 'ARM64')) {
        throw "Unsupported architecture: $Arch."
    }
    if ($Arch -eq 'ARM64') {
        $AssetArch = 'arm64'
    } else {
        $AssetArch = 'amd64'
    }
    Write-Info "platform: windows/$AssetArch"

    # ── Version ──────────────────────────────────────────────────────────────
    $Version = Resolve-BoxyVersion
    Write-Info "version: $Version"
    $VersionNum = $Version.TrimStart('v')
    $Archive    = "boxy_${VersionNum}_windows_${AssetArch}.zip"
    Write-Dbg "archive=$Archive"

    # ── Download URLs ────────────────────────────────────────────────────────
    $DownloadBase = if ($BaseUrl) { "$BaseUrl/$Repo/releases/download" } else { "https://github.com/$Repo/releases/download" }
    $ArchiveUrl   = "$DownloadBase/$Version/$Archive"
    $ChecksumUrl  = "$DownloadBase/$Version/checksums.txt"

    # ── Temp directory ───────────────────────────────────────────────────────
    $TmpDir = Join-Path ([System.IO.Path]::GetTempPath()) ("boxy-install-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $TmpDir | Out-Null
    $ArchivePath   = Join-Path $TmpDir $Archive
    $ChecksumsPath = Join-Path $TmpDir 'checksums.txt'

    # ── Download ─────────────────────────────────────────────────────────────
    Write-Info "Downloading $Archive..."
    Write-Dbg "url=$ArchiveUrl"
    Copy-ReleaseAsset $ArchiveUrl  $ArchivePath
    Copy-ReleaseAsset $ChecksumUrl $ChecksumsPath

    # ── Verify ───────────────────────────────────────────────────────────────
    Write-Info 'Verifying checksum...'
    $Expected = Get-ExpectedChecksum $ChecksumsPath $Archive
    if (-not $Expected) { throw "Checksum for $Archive not found in checksums.txt." }
    Test-Checksum $ArchivePath $Expected
    Write-Ok 'checksum ok'

    # ── Install ──────────────────────────────────────────────────────────────
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    $BinaryDest = Join-Path $InstallDir 'boxy.exe'
    if ((Test-Path $BinaryDest) -and -not $IsForce) {
        throw "$BinaryDest already exists. Set BOXY_FORCE=1 to overwrite."
    }

    $ExtractDir = Join-Path $TmpDir 'extract'
    Expand-Archive -Path $ArchivePath -DestinationPath $ExtractDir -Force
    Copy-Item -Path (Join-Path $ExtractDir 'boxy.exe') -Destination $BinaryDest -Force

    Write-Ok "boxy $Version installed to $BinaryDest"
    if (-not (Test-InPath $InstallDir)) { Show-PathInstructions $InstallDir }

    Write-Host ''
    Write-Host 'Done! ' -ForegroundColor Green -NoNewline
    Write-Host "Run 'boxy --help' to get started."
} finally {
    if ($TmpDir -and (Test-Path $TmpDir)) { Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue }
}
